name: Build docs from trunk

on:
  push:
    branches:
      - master

# we set this not to stuck in a state after clearing s3 folder and before filling it with new files
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-docs-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install -E "all docs" -vv
      - name: Install apt docs dependencies
        run: |
          sudo apt install pandoc
          sudo apt install s3cmd
      - name: Build docs
        run: |
          cd docs
          poetry run make build-docs
          mv build/html/ ../site
        env:
          CI_COMMIT_SHORT_SHA: ${{ github.sha }}
          WORKFLOW_NAME: ${{ github.workflow }}
      - name: Deploy to s3
        run: |
          echo "${{ secrets.DOCS_S3CMD_CONFIG }}" > .s3cfg
          s3cmd -c .s3cfg rm -r "s3://docs.etna.ai/latest/"
          s3cmd -c .s3cfg put --recursive --guess-mime-type --no-mime-magic ./site/ "s3://docs.etna.ai/latest/"
